#include "../../pushswap/includes/utils.h"
#include "../../pushswap/includes/myloc.h"

int main() {
    t_stack *Astack = initStack('a');
    printf("stack On %p and values %p size : %d name : %c\n", &Astack, Astack, Astack->size, Astack->name);
    t_stack *Bstack = initStack('b');
    printf("stack On %p and values %p size : %d name : %c\n", &Bstack, Bstack, Bstack->size, Bstack->name);
    addBack(Astack->list, 1);
    addBack(Astack->list, 2);
    addBack(Astack->list, 3);
    addBack(Astack->list, 4);
    Astack->size = 4;
    printf("Original Astack\n");
    traverseAll(Astack->list);
    sa(Astack);
    printf("Start sa\n");
    traverseAll(Astack->list);
    addBack(Bstack->list, 5);
    addBack(Bstack->list, 6);
    addBack(Bstack->list, 7);
    addBack(Bstack->list, 8);
    Bstack->size = 4;
    printf("Original Bstack\n");
    traverseAll(Bstack->list);
    sb(Bstack);
    printf("Start sb\n");
    traverseAll(Bstack->list);
    ss(Astack, Bstack);
    printf("Start ss\n");
    traverseAll(Astack->list);
    traverseAll(Bstack->list);
    printf("Start pa\n");
    pa(Astack, Bstack);
    traverseAll(Astack->list);
    traverseAll(Bstack->list);
    printf("Start pb\n");
    pb(Astack, Bstack);
    traverseAll(Astack->list);
    traverseAll(Bstack->list);
    printf("Start ra\n");
    ra(Astack);
    traverseAll(Astack->list);
    printf("Start ra2\n");
    ra(Astack);
    traverseAll(Astack->list);
    printf("Start ra4\n");
    ra(Astack);
    ra(Astack);
    traverseAll(Bstack->list);
    printf("Start rb\n");
    rb(Bstack);
    traverseAll(Bstack->list);
    printf("Start rb2\n");
    rb(Bstack);
    traverseAll(Bstack->list);
    printf("Start rb4\n");
    rb(Bstack);
    rb(Bstack);
    traverseAll(Bstack->list);
    printf("Start rr\n");
    rr(Astack, Bstack);
    traverseAll(Astack->list);
    traverseAll(Bstack->list);
    printf("Start rra\n");
    rra(Astack);
    traverseAll(Astack->list);
    printf("Start rra2\n");
    rra(Astack);
    traverseAll(Astack->list);
    printf("Start rra4\n");
    rra(Astack);
    rra(Astack);
    rra(Astack);
    traverseAll(Astack->list);
    printf("Start rrb\n");
    rrb(Bstack);
    traverseAll(Bstack->list);
    printf("Start rrb2\n");
    rrb(Bstack);
    traverseAll(Bstack->list);
    printf("Start rrb4\n");
    rrb(Bstack);
    rrb(Bstack);
    rrb(Bstack);
    traverseAll(Bstack->list);
    rr(Astack, Bstack);
    rrr(Astack, Bstack);
    traverseAll(Astack->list);
    traverseAll(Bstack->list);
    pb(Astack, Bstack);
    pb(Astack, Bstack);
    traverseAll(Astack->list);
    ra(Astack);
    traverseAll(Astack->list);
    ra(Astack);
    traverseAll(Astack->list);
    clearStacks(&Astack, &Bstack);
    printf("Astack on %p and value %p\n", &Astack, Astack);
    printf("Bstack on %p and value %p\n", &Bstack, Bstack);
    return 0;
}
